// Mocks generated by Mockito 5.4.4 from annotations
// in stopwatch_challenge/test/data/mock_stopwatch_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:stopwatch_challenge/data/stopwatch_service.dart' as _i2;
import 'package:stopwatch_challenge/models/saved_stopwatch.dart' as _i5;
import 'package:stopwatch_challenge/models/stopwatch_model.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [StopwatchService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStopwatchService extends _i1.Mock implements _i2.StopwatchService {
  MockStopwatchService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveStopwatch({
    required _i4.StopwatchModel? stopwatchModel,
    required int? bestLap,
    required int? worstLap,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveStopwatch,
          [],
          {
            #stopwatchModel: stopwatchModel,
            #bestLap: bestLap,
            #worstLap: worstLap,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.SavedStopwatch>> getSavedStopwatches() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSavedStopwatches,
          [],
        ),
        returnValue:
            _i3.Future<List<_i5.SavedStopwatch>>.value(<_i5.SavedStopwatch>[]),
      ) as _i3.Future<List<_i5.SavedStopwatch>>);

  @override
  _i3.Future<void> deleteSavedStopwatches() => (super.noSuchMethod(
        Invocation.method(
          #deleteSavedStopwatches,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
