name: stopwatch_challenge
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  injectable: ^2.3.2
  intl: ^0.19.0
  json_annotation: ^4.8.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  analyzer: ^6.4.1
  build_runner: ^2.4.8
  fake_async: ^1.3.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
